server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/blog
    password: 12345
